# Generated by Django 6.0.2 on 2026-02-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='reading_goals',
            new_name='reading_goal',
        ),
    ]
